server:
  port: 0

spring:
  application:
    name: resqueue-user

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KC_BASE_ISSUER_URL:http://localhost:9000}/realms/resqueue

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}

keycloak:
  base-url: ${AUTH_BASE_URL:http://localhost:9000}
  client-id: resqueue-client
  client-secret: ${AUTH_RESQUEUE_CLIENT_SECRET}

springdoc:
  api-docs:
    enabled: true
    path: /users/v3/api-docs
  swagger-ui:
    enabled: true
    path: /docs
    config-url: /users/v3/api-docs/swagger-config
    urls:
      - name: users-service
        url: /users/v3/api-docs
